import {HushhButton} from "../svg/icons/HeaderIcons/HushhButton";
import {HushhWalletApp} from "../svg/icons/HeaderIcons/HushhWalletApp";
import { ConciergeApp } from "../svg/icons/HeaderIcons/ConciergeApp";
import {ChromeExtension} from "../svg/icons/HeaderIcons/ChromeExtension";
import { ValetChat } from "../svg/icons/HeaderIcons/ValetChat";
import { VibeSearchApp } from "../svg/icons/HeaderIcons/VibeSearchApp";
import HfsLogo from "../svg/hfsLogo";

const contentMap = [
  {
    keywords: ["hushh button","Gen AI", "Hushh Button For Customers", "Hushh Button For Brands", "Brands", "Customers"],
    url: "/products/hushhButton",
    content: "share data for personalized reccomendations , Imagine a world where shopping feels effortless and tailored just for you. Hushh Button, a powerful plugin, bridges the gap between your preferences/choices/needs/likes and your favourite brands , Seamless Data Sharing for Personalized Experiences with Gen AI, Hushh is your one-stop solution for seamless data sharing between you and your favorite websites. With Hushh, you can effortlessly share your personal data with brands to enhance your browsing experience and receive tailored recommendations , Sync your preferences, past purchases, sizing information to brands with a single click , Get your brand-specific data sent directly to your Hushh Wallet for secure storage and management , Brands can offer products and services based on your unique profile, leading to a more relevant shopping experience , Hushh Button for brands , Access authentic data from Hushh users who opt-in, allowing for personalized product recommendations and marketing campaigns , Simplified data collection and ensures compliance with user privacy preferences , Create a more personalized and rewarding shopping experience that drives loyalty and sales , Customers enjoy a seamless and personalized shopping experience, while brands gain valuable insights and build stronger relationships with their audience , Transformed Shopping Experience , With the Hushh Widget, websites and apps seamlessly change to showcase products that align with the user's preferences. It's like having a personalized shopping assistant that curates recommendations based on their unique style , Hushh Button Magic , The widget allows users to create their cookies and control what information they want to share with different websites. This gives users complete control over their data privacy while enjoying a personalized shopping experience , Data Retrieval Made Easy , The widget allows users to create their cookies and control what information they want to share with different websites. This gives users complete control over their data privacy while enjoying a personalized shopping experience ",
    showRecommentationContentHeading:'Hushh Button',
    showRecommentationContentDescription: 'share data for personalized reccomendations',
    icon:<HushhButton/>,
  },
  {
    keywords: [" Hushh Wallet App", "Gen AI","Customer user flow + Client Advisor User flow", "Data Wallet", "AI" , "YOUR PERSONAL DATA"],
    url:"/products/hushhWalletApp",
    content: "Higher perk adoption, instant expense management, simple benefits access and much more , World's first AI Powered Data Wallet , Your Personal Data , Your OWN Business , Imagine a world where your data works for you, not against you. A world where your online and offline interactions paint a detailed picture of your unique self, accessible only by you and those you choose to trust. This is the reality unlocked by Hushh Wallet, the app that puts you in control of your digital identity and empowers you to reap the rewards it holds. , Scattered Data, Unified Identity , Every brand you interact with, every click you make, every purchase you complete leaves a digital footprint. Your personality, preferences, buying power, and interests are scattered across phones, platforms, and brands, often inaccessible and invisible to you. Hushh Wallet bridges this gap. It aggregates your data from various sources, including , Phone data ,Text messages, location, images, emails, call records, documents, videos, notes, etc , Data companies , Shopping brands , Online e-commerce sites, apps, and offline receipts , With Hushh, you become the curator of your own identity. You choose what information to include, building a comprehensive profile that reflects your true self , More Than Just an App , Hushh Wallet is more than just an app; it's a paradigm shift. It empowers you to , Take ownership of your digital identity with Gen AI , Build meaningful connections , Unlock the true potential of your data , Receipt radar , Personalized Experiences , Rewarded Interactions , Gone are the days of irrelevant ads and generic recommendations. Hushh allows you to create data cards containing specific information you're comfortable sharing. Now, you can , Connect with brands and sales agents you trust , Share your curated data cards with businesses you choose, enabling them to offer personalized experiences and recommendations tailored to your unique preferences , Get rewarded for sharing data , Earn rewards for the valuable information you contribute, be it discounts, exclusive offers, or early access to products , Sell your data , You can sell your data directly to brands and agencies, receiving fair compensation for its value , Transparency and Control , Hushh prioritizes your privacy and control. You have full transparency over who has access to your data and what they can see. You can easily revoke access or modify your data cards at any time , Enter a world made for you , Download Hushh Wallet today and unlock the power of your personal data , ",
    showRecommentationContentHeading:'Hushh Wallet App',
    showRecommentationContentDescription: "World's First Gen AI Powered Data Wallet",
    icon:<HushhWalletApp/>,
  },
  {
    keywords:["Data Value Setting", "Gen AI","Hushh For Students", "HFS","Secure Data Exchange", "Rewards and Points System", "Developers", "Business"],
    url:"/products/hushhForStudents",
    content:"Hushh For Students ,  Empowering and rewarding digital engagement , HFS , Secure Data Exchange , data exchange by empowering students with Gen AI  , Hushh for students: Revolutionizing data exchange by empowering students and providing businesses with valuable insights, balancing rewards and privacy ,  Hushh elevates your experience , Our technology services deliver cutting-edge solutions tailored to drive efficiency, enhance performance, and fuel growth in today's digital landscape , Data Value Setting , Students have the ability to set a value for their data, establishing both transparency and control over it , The platform enables businesses to securely purchase data from students. This process is designed to ensure data privacy and secure transactions , Students earn rewards and points for each successful data transaction they partake in. This system incentivizes them to participate in the data exchange , Control your data, earn rewards – hushh for students makes your data work for you , Hushh caters to a wide range of needs, including , Students , Bespoke itineraries, private jet charters, exclusive tours , Purchase valuable student data for various purposes, benefiting from access to targeted data. Access to valuable student data for targeted initiatives. Seamless and secure data exchange process , student's data , Working on a cutting-edge platform that blends data exchange with user empowerment offers a unique opportunity for technical creativity and innovation ,   ",
    showRecommentationContentHeading:'Hushh For Students',
    showRecommentationContentDescription: "Empowering, rewarding digital engagement & Revolutionizing data exchange by empowering students with Gen AI",
    icon:<HfsLogo style={{width:"25", height:"25"}}/>,
  },
  {
    keywords:["Vibe Search","latest trends","Gen AI", "fashion" , "fashion and style" , "outfits", "personalized", "personalised", "favorite products" , "shopping experience" , "Find Your Style", "fashion companion", "liked items", "up to date", ""],
    url:"/products/vibeSearch",
    content:"Vibe Search ,  Vibe , Vibe Recommedations , The vibe search app lets find and store all your favorite products that you come across by just taking a picture or by typing , Introducing Vibe search your companion for fashion and style ,  Want to know where you can buy that cute dress you saw the other day? don’t know what style fits you best . Don,t worry vibe search is all you need . VIbe search is your fashion companion that helps you find your style , style , fashion style , shopping experience , Find Your Style with , Your own Stylist ,  Find The Style that fits you best , outfit , Our Gen AI products based on image and text , Save all your liked products , Get insights on your Fit and Style , Share your best Fit with Family and Friends , Find that perfect Fit and perfect look with just a click of a button. Search products with just and image and text save them for later to buy or create a whilst to share it with friends and family , Vibe Search Integration ,  Integrate You Vibe with Vibe Search , Hushh vibe search also enables users to share your style preferences in their Hushh Wallet. This makes it easy to share and access important information, such as Your Size, FIt, Brands , Budget and Purchase history , More Than Just an app , Vibe search is more than just an app its your personal stylist on tap of a button , Your Personal Fashion Stylist at your Fingertips ,  The Vibe search utilizes advanced algorithms and AI technology to analyze the captured data Fid the best fit and style for you. Users receive personalized recommendations, discover new products and brands aligned with their interests, and stay up-to-date with the latest trends with Gen AI    ",
    showRecommentationContentHeading:'Vibe Search App',
    showRecommentationContentDescription: "Personalized search engine that lets you search across brands",
    icon:<VibeSearchApp/>,
  },
  {
    keywords:["Valet Chat App", "finance","Gen AI", "Manage finance", "Convenient Wallet Integration", "Intelligent Finance and Receipts Management", "Collect receipts from mail"],
    url:"/products/hushhValetChat",
    content:"Valet Chat App ,  Hushh Valet Chat , Lets you collect all your receipts from mail and manage them to help you better understand your spending habits and finance with Gen AI , Manage all your receipts at one place and get insights on your finance with Gen AI , Tired of? all the receipts at your mail and don't know how to manage them ? Valet chat is your one stop solution to find and manage all your receipts at one place and also get useful insights from us to better manage your finance , Valet chat helps you manage finance , Track your recipts , Sync all your receipts automatically , Chat with our AI to understand your Finances better , Manage and categories receipts for easy access , Share your receipts with people and receive insights , Convenient Wallet Integration , Streamlined Integration via Valet Chat ,  Hushh Valet chat also enables users to share their Reciepts in their Hushh Wallet. This makes it easy to organize and access important information, such as receipts, warranty details, and more, all in one secure place , Intelligent Finance and Receipts Management , The Valet chat app utilizes advanced algorithms and AI technology to analyze the captured data and generate brilliant insights. Users receive personalized Insights on receipts, Manage their Receipts and receive intelligent insights on their spendings and Finance ",
    showRecommentationContentHeading:'Valet Chat App',
    showRecommentationContentDescription: "Lets you collect all your receipts from mail and manage them to help you better understand your spending habits and finance",
    icon:<ValetChat/>,
  },
  {
    keywords:["Concierge App", "luxury experience","Gen AI",  "real time data", "Real-Time Matching", "Powered by AI" , "Flips the Script", "Exclusive Opportunities", "Discretion and Privacy", "Personalized Recommendations","Effortless Service" ],
    url:"/products/conciergeApp",
    content:"Concierge App , Experience Luxury, Redefined , Hushh is a revolutionary concierge app that transforms luxury experiences through the power of voice, AI, and real-time data with Gen AI. Unlike traditional concierge services, Hushh prioritizes your needs, not just your preferences with Gen AI , Our technology services deliver cutting-edge solutions tailored to drive efficiency, enhance performance, and fuel growth in today's digital landscape , Effortless Service , Simply speak your request using the app, and Hushh translates it into action. No more searching or filling out forms , Personalized Recommendations , Hushh analyzes your intent, not just your preferences, to recommend services that truly match your needs , Real-Time Responses , Get immediate responses to your requests from top-tier service providers, competing for your attention , Discretion and Privacy , Your identity and preferences remain confidential. Requests are shared anonymously with relevant service providers , Exclusive Opportunities , Access exclusive deals and hidden gem recommendations you won't find anywhere else , Hushh caters to a wide range of needs, including - Travel ,  Bespoke itineraries, private jet charters, exclusive tours , Events , VIP access to high-profile events, private viewings, red carpet experiences , Lifestyle , Personal shopping, home management, day-to-day errands, specialized requests , Receipt Radar revolutionizes the way you handle receipts. With automatic scanning, smart categorization, and customizable options, managing expenses becomes a breeze. Simplify your life and take control of your finances with Receipt Radar today! , Flips the Script , Users seeking services become services seeking users, putting you in control , Powered by AI , Leverages cutting-edge technology to understand your intent and deliver personalized recommendations , Real-Time Matching , Connects you with the right service providers instantly ",
    showRecommentationContentHeading:'Concierge App',
    showRecommentationContentDescription: "Speak your wish and get experience Luxury, Redefined by priotizing your needs and preferences through the power of voice, Gen AI, and real-time data",
    icon:<ConciergeApp/>,
  },
  {
    keywords:["Browser Companion", "Chrome Extension", "Gen AI","Digital footprint", ""],
    url:"/products/browserCompanion",
    content:"Tired of being tracked online? Every click, scroll, and search query leaves a trail of your identity, exploited by third-party organizations for targeted advertising. With Hushh, the power is back in your hands , Browser Companion , Chrome Extension , Tired of being tracked online? Every click, scroll, and search query leaves a trail of your identity, exploited by third-party organizations for targeted advertising with Gen AI features. With Hushh, the power is back in your hands , Introducing Hushh Browser Companion, a product that helps you keep track of your digital footprint with Gen AI , Tired of being tracked online? Every click, scroll, and search query leaves a trail of your identity, exploited by third-party organizations for targeted advertising. With Hushh, the power is back in your hands , Track your own browsing activity , Choose what data to collect , Track your interests over time , Export the collected data to your hushh wallet , Sell your data responsibly and get tailored services , Convienient Wallet Integration , Hushh Web Browser Companion also enables users to share their user activity in their Hushh Wallet. This makes it easy to organize and access important information, such as receipts, warranty details, and more, all in one secure place , Intelligent Insights and Recommendations , The extension utilizes advanced algorithms and AI technology to analyze the captured data and generate brilliant insights. Users receive personalized recommendations, discover new products and brands, aligned with their interests, and stay up-to-date with the latest trends",
    showRecommentationContentHeading:'Browser Companion',
    showRecommentationContentDescription: "Enhanced Recommendations and impactful marketing which helps you keep track of your digital footprint by tracking your own browsing activity",
    icon:<ChromeExtension/>,
  }

];

export default contentMap;
