import { advisoryImages } from "../features/teamImages";
import { teamImages } from "../features/teamImages";

export const advisorsData = [
  {
    name: "Suresh Attuluri",
    position: "Technology Advisor - Engineering",
    linkedin: "https://www.linkedin.com/in/sureshattuluri/",
    imageSrc: advisoryImages.suresh,
    currentWork: "Vice President of Software Engineering @ Wheels Up",
    currentLocation: "Sammamish, Washington, United States",
    avatar: teamImages.AkashKatla,
  },
  {
    name: "Mark McLaughlin",
    position: "Advisor to the CEO",
    linkedin: "https://www.linkedin.com/in/markmclaughlin4/",
    imageSrc: advisoryImages.markMc,
    currentWork: "Chairman Of The Board @ Qualcomm",
    currentLocation: "Santa Clara, California, United States",
    avatar: teamImages.AnkitKumarSingh,
  },
  {
    name: "Mark Groves",
    position: "Technology Advisor - Products",
    linkedin: "https://www.linkedin.com/in/mark-groves/",
    imageSrc: advisoryImages.markGroves,
    currentWork: "Retired | DocuSign",
    currentLocation: "Pagosa Springs, Colorado, United States",
    avatar: teamImages.AnuragGhose,
  },
  {
    name: "Dan Sareen",
    position: "GTM Advisor - Ecosytems and Partnerships",
    linkedin: "https://www.linkedin.com/in/dan-sareen-95259a274/",
    imageSrc: advisoryImages.danSareen,
    currentWork: "Market Development Director @ Accenture",
    currentLocation: "Greater Houston, Texas, United States",
    avatar: teamImages.ApoorvBedmutha,
  },
  {
    name: "Andrew Stein",
    position: "Technology Advisor - Products",
    linkedin: "https://www.linkedin.com/in/ahstein/",
    currentWork: "Group Product Manager at Cross Google Engineering & Core",
    currentLocation: "Greater Seattle Area",
    imageSrc: advisoryImages.andrew,
    avatar: teamImages.DeveshParagiri,
  },
  {
    name: "Stéphane Spinella",
    position: "GTM Advisor - EMEA Sales and Business Development",
    linkedin: "https://www.linkedin.com/in/stephanespinella/",
    imageSrc: advisoryImages.stephane,
    currentWork: "Senior Director,Enterprise Sales @ Brickster | ex-Google",
    currentLocation: "Paris, Île-de-France, France",
    avatar: teamImages.KaranSoni,
  },
  {
    name: "Amit Fulay",
    position: "Technology Advisor - Products",
    linkedin: "https://www.linkedin.com/in/afulay/",
    imageSrc: advisoryImages.amitFulay,
    currentWork: "Vice President of Product @ Microsoft",
    currentLocation: "Greater Seattle Area",
    avatar: teamImages.KarthickMuthu,
  },
  {
    name: "Rish Tandon",
    position: "Technology Advisor - Products",
    linkedin: "https://www.linkedin.com/in/rishtandon/",
    imageSrc: advisoryImages.rishi,
    currentWork: "Vice President @ Meta",
    currentLocation: "Greater Seattle Area",
    avatar: teamImages.NeeleshMeena,
  },
  {
    name: "Valliappa Lakshmanan",
    position: "Technology Advisor - AI/ML, Data and Analytics",
    linkedin: "https://www.linkedin.com/in/valliappalakshmanan/",
    imageSrc: advisoryImages.valliappa,
    currentLocation: "Bellevue, Washington, United States",
    currentWork: "Operating Executive - Data Science @ Silver Lake",
    avatar: teamImages.OmkarKailasMalpure,
  },
  {
    name: "Sudhir Hasbe",
    position: "Technology Advisor - Products",
    linkedin: "https://www.linkedin.com/in/shasbe/",
    currentWork:
      "Chief Product Officer @ Neo4j, ex-Sr. Director of Product Management @ Google",
    currentLocation: "Mercer Island, Washington, United States",
    imageSrc: advisoryImages.sudhir,
    avatar: teamImages.SatyamArora,
  },
  {
    name: "Samant Nagpal",
    position: "Business Advisor - Corporate Risk",
    linkedin: "https://www.linkedin.com/in/samant-nagpal-3240683/",
    imageSrc: advisoryImages.samant,
    currentWork: "Chief Risk Officer @ Square",
    currentLocation: "Kirkland, Washington, United States",
    avatar: teamImages.SubashManoharan,
  },
  {
    name: "Daniel Cleveland",
    position: "Business Advisor - Finance",
    linkedin: "https://www.linkedin.com/in/danielcleveland/",
    imageSrc: advisoryImages.daniel,
    currentWork: "Group Finance Manager @ Microsoft | ex-Google",
    currentLocation: "Washington DC-Baltimore Area",
    avatar: teamImages.YashMakan,
  },
  {
    name: "Nilanshu Raja",
    position: "Business Advisor  - Finance",
    linkedin: "https://www.linkedin.com/in/nilanshu/",
    imageSrc: advisoryImages.nilanshu,
    currentWork: "Chief Financial Officer @ Super (hellosuper.com)",
    currentLocation: "San Francisco Bay Area",
    avatar: teamImages.AkashKatla,
  },
];
